### ISSUE TITLE
Pydio sharing feature is disabled

### ISSUE THREAD

**Issue by G-Ray** [Toilal/stealthbox#17]
I tried to play with sharing options here: [url]:8443/settings/config/core, without success.

If we put "/home/box/pydio/public" as the public folder, the sharing button appears, but the sharing link points to a 404.

**Comment by Toilal** [comment]
I can reproduce the issue. I'm not sure it's related to docker image or Pydio only.

**Comment by Toilal** [comment]
I think it's related to nginx proxy.

**Comment by Toilal** [comment]
You still need to configure options related to sharing, but it will work using nginx configuration from latest master.

From bash, you can copy the configuration https://github.com/Toilal/stealthbox/blob/master/nginx/stealthbox to `/etc/nginx/sites-available/stealthbox` in a running container, and then restart nginx service using `service nginx restart`.

**Comment by Toilal** [comment]
Configure the download URL to `https://your-server/public/`, and Download folder to `home/box/pydio/public`
