### ISSUE TITLE
Sonarr (instead of Sick-Rage?)

### ISSUE THREAD

**Issue by jkaberg** [Toilal/stealthbox#21]
First off, nice work. Seems like quite the beast

But might I suggest moving to Sonarr instead? 

https://github.com/Sonarr/Sonarr

**Comment by Toilal** [comment]
I did not know Sonarr, but it seems to be a great tool ... I think i'll create a branch with this tool instead of sickrage to evaluate it. If it really outperform sickrage, it will becomz the default. 

I don't have time for now, hope i'll be able to work on this in the next few weeks.

**Comment by Toilal** [comment]
Sonarr is coded with C# and use Mono in linux. Not really a good news ...

**Comment by Toilal** [comment]
But seems easy to install though : https://github.com/Sonarr/Sonarr/wiki/Installation#linux

**Comment by dm-coding** [comment]
Perhaps this could help? https://github.com/tuxeh/docker-sonarr

**Comment by Toilal** [comment]
I'm working on Stealthbox 2 which will be based on `docker-compose`, and Sonarr will be here.

It's currently already available in `2.x` branch, but there are some features missing from previous version, like changing password and docs :).

**Comment by jkaberg** [comment]
I recomend you include [Jackett](https://github.com/Jackett/Jackett) aswell, Sonarr and torrents is a lot better with it.

**Comment by Toilal** [comment]
Well, 4 years later I have rewrite stealthbox from scratch using jackett, sonarr, radarr and lidarr.

It now requires a wildcard domain name and a dedicated server to work properly.

[Docker Devbox](https://github.com/gfi-centre-ouest/docker-devbox) has to be installed on the host, it's a tool that automate any docker based project. It's powered by [docker](https://www.docker.com/), [Traefik](https://traefik.io) and [ddb](https://gfi-centre-ouest.github.io/docker-devbox-ddb/) to provide automation of complex docker-compose projects, so you can host all containers behind a secure domain name (SSL Certicate is automatically generated with Traefik+Letsencrypt) and don't mess with so common docker permissions issues.

I'll provide a **standalone** and a **traefik** version later so users can run stealthbox without [Docker Devbox](https://github.com/gfi-centre-ouest/docker-devbox) installed.
