### ISSUE TITLE
Fail to start (loop)

### ISSUE THREAD

**Issue by scith** [Toilal/stealthbox#22]
Hello and thanks for this amazing container!
When I restarted my server, the container got stuck on "restart" status. I looked at the logs and here is what seems to happen:

> **\* Killing all processes...
> **\* Running /etc/my_init.d/000_before_regen_ssh_host_keys.sh...
> **\* Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
> **\* Running /etc/my_init.d/10-ssl.sh...
> SSL Certificate are available in /etc/stealthbox/ssl.
> **\* Running /etc/my_init.d/20-configure.sh...
> Shell is NON interactive.
> Set password using PASSWORD environment variable.
> Changing password...
> (current) UNIX password: Enter new UNIX password: Retype new UNIX password: Password unchanged
> Enter new UNIX password: Retype new UNIX password: passwd: Authentication token manipulation error
> passwd: password unchanged
> Changing password for box.
> **\* /etc/my_init.d/20-configure.sh failed with status 10

I ran the container using the "PASSWORD=" feature.
Any idea?
Thanks

**Comment by Toilal** [comment]
I'll try to give a try to `PASSWORD=` feature ... The bug is probably related to that.

**Comment by Toilal** [comment]
What's the OS of your host. It works here, using ubuntu 14.04.

**Comment by scith** [comment]
Hello, I have Debian Jessie. But the problem hasn' occured since when I reported the bug, although I have restarted the server multiple times since... I guess you can close the issue but I have no idea why it did it in the first place.
If it ever happens again I'll try to reproduce and reopen the issue

Thanks
