### ISSUE TITLE
Use Docker Compose

### ISSUE THREAD

**Issue by Toilal** [Toilal/stealthbox#23]
It would be better to split the project in various docker images, and use Docker Compose to start the whole thing. It will make it easier to enable/disable some components for each user.

@see http://blog.hypriot.com/post/docker-compose-nodejs-haproxy/

**Comment by sirago** [comment]
This still happening?

**Comment by Toilal** [comment]
Sorry, i've no time to spend on stealthbox at the moment, but it's still planned :)

**Comment by Toilal** [comment]
It's happening, work in progress is in 2.x branch. Currently there's an unconfigured pydio running in the compose configuration.

But I still have some work to make all previous features work in this new architecture.

**Comment by Toilal** [comment]
Also I don't know how to publish the whole thing to docker hub, using automated build feature.

**Comment by micheldlebeau** [comment]
You might want to take a look at https://docs.docker.com/docker-hub/builds/  

Great job anyway!

**Comment by Toilal** [comment]
It' now running with docker-compose.
