### ISSUE TITLE
Exec format error on ARM

### ISSUE THREAD

**Issue by dm-coding** [Toilal/stealthbox#24]
Hi there,

I'm having trouble building your docker image on an ARM server:

root@daedalus ~/stealthbox# docker build -t stealthbox .
Sending build context to Docker daemon 239.6 kB
Sending build context to Docker daemon 
Step 0 : FROM phusion/baseimage:0.9.16
0.9.16: Pulling from phusion/baseimage
511136ea3c5a: Pull complete 
53f858aaaf03: Pull complete 
837339b91538: Pull complete 
615c102e2290: Pull complete 
b39b81afc8ca: Pull complete 
8254ff58b098: Pull complete 
ec5f59360a64: Pull complete 
2ce4ac388730: Pull complete 
2eccda511755: Pull complete 
5a14c1498ff4: Already exists 
Digest: sha256:f55d261778d83def4a60d38939511cbed0268fcb91383c9e3edf2877ced289d9
Status: Downloaded newer image for phusion/baseimage:0.9.16
 ---> 5a14c1498ff4
Step 1 : MAINTAINER Rémi Alvergnat toilal.dev@gmail.com
 ---> Running in cdf1e20a7125
 ---> 81bc89383a8f
Removing intermediate container cdf1e20a7125
Step 2 : CMD /sbin/my_init
 ---> Running in 68990055d48c
 ---> 0499e25c49e0
Removing intermediate container 68990055d48c
Step 3 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in d220fa46de2f
 ---> b6d6407c2f3a
Removing intermediate container d220fa46de2f
Step 4 : ENV HOME /root
 ---> Running in 84349399365f
 ---> e63542ff9420
Removing intermediate container 84349399365f
Step 5 : RUN rm -f /etc/apt/apt.conf.d/docker-gzip-indexes
 ---> Running in af7328358020
exec format error
INFO[0141] [8] System error: exec format error   

I'm a bit new to Docker and not sure what I should do to make it work.

**Comment by ypid** [comment]
Related to https://github.com/kfei/docktorrent/issues/29 (@djcf One issue would have been enough :smile: )

**Comment by dm-coding** [comment]
Thanks for your patience @ypid. Issued resolved with sdhibit's Debian raspberry-pi baseimage, i.e.,

FROM sdhibit/rpi-baseimage

in Dockerfile.
