### ISSUE TITLE
Problems running pydio

### ISSUE THREAD

**Issue by dm-coding** [Toilal/stealthbox#25]
Pydio screen is just blank, no output. No interesting information in syslog, /var/log/nginx, /var/log/php5-fpm.log, /home/box/pydio/logs, or /home/box/nginx/error.pydio.log.

Possibly alluded to: https://github.com/Toilal/stealthbox/issues/20

**Comment by Toilal** [comment]
Hi ! I'm sorry I can't reproduce it. I've also upgrade to pydio 6.2.2 in develop branch, it'll be released soon.

Reopen if you still have this issue.
