### ISSUE TITLE
Password manipulation error on startup

### ISSUE THREAD

**Issue by dm-coding** [Toilal/stealthbox#26]
When I stop and then start the container, I get this message in the log files:

**\* Killing all processes...
**\* Running /etc/my_init.d/000_before_regen_ssh_host_keys.sh...
**\* Running /etc/my_init.d/10-ssl.sh...
SSL Certificate are available in /etc/stealthbox/ssl.
**\* Running /etc/my_init.d/20-configure.sh...
Shell is NON interactive.
Set password using PASSWORD environment variable.
Changing password...
(current) UNIX password: Enter new UNIX password: Retype new UNIX password: Password unchanged
Enter new UNIX password: Retype new UNIX password: passwd: Authentication token manipulation error
passwd: password unchanged
Changing password for box.
**\* /etc/my_init.d/20-configure.sh failed with status 10

**\* Killing all processes...

**Comment by Toilal** [comment]
Fixed
